R1= 120; % NEW EFFECTIVE RESISTOR
V= 0:240; % VOLTAGE
I= V/R1; % CURRENT
P= (I.^2)*R1; % POWER
plot(I,P); % PLOTING GRAPH BETWEEN POWER AND CURRENT
xlabel('CURRENT (I)'), ylabel('POWER (P)'), title('POWER-CURRENT'), grid on